name: AI Agent Workflow

on:
  push:
    branches: [main]

jobs:
  ai-agent:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files (DEBUG STEP)
        run: ls -R

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run basic check
        run: echo "Code pushed successfully 🚀"

      - name: Run Python file
        run: python app.py

      - name: AI Code Review
        run: |
          echo "Pretend AI is reviewing code"
          cat app.py